$encUtf8 = New-Object System.Text.UTF8Encoding $true
$file1 = 'c:\Users\Admin\Desktop\progtram\Cow\Source\ResultScene.cpp'
$content1 = [System.IO.File]::ReadAllText($file1)
$content1 = $content1.Replace("isHover", "is_hover")
$content1 = $content1.Replace("mButtons", "buttons_")
$content1 = $content1.Replace("mFadeState", "fade_state_")
$content1 = $content1.Replace("SceneFade_In", "kSceneFadeIn")
$content1 = $content1.Replace("SceneFade_Out", "kSceneFadeOut")
$content1 = $content1.Replace("SceneFade_None", "kSceneFadeNone")
$content1 = $content1.Replace("ResultGraphHandle", "result_graph_handle_")
$content1 = $content1.Replace("yourScoreTextImg", "your_score_text_img_")
$content1 = $content1.Replace("pointImg", "point_img_")
$content1 = $content1.Replace("mNextScene", "next_scene_")
$content1 = $content1.Replace("SCENE_TITLE", "kSceneTitle")
$content1 = $content1.Replace("rankingTitleImage", "ranking_title_image_")
$content1 = $content1.Replace("rankImage", "rank_image_")
$content1 = $content1.Replace("mnCount", "count_")
$content1 = $content1.Replace("yourScoreImage", "your_score_image_")

[System.IO.File]::WriteAllText($file1, $content1, $encUtf8)

$file2 = 'c:\Users\Admin\Desktop\progtram\Cow\Source\TitleScene.cpp'
$content2 = [System.IO.File]::ReadAllText($file2)
$content2 = $content2.Replace("isHover", "is_hover")
$content2 = $content2.Replace("mButtons", "buttons_")
$content2 = $content2.Replace("mFadeState", "fade_state_")
$content2 = $content2.Replace("SceneFade_In", "kSceneFadeIn")
$content2 = $content2.Replace("SceneFade_Out", "kSceneFadeOut")
$content2 = $content2.Replace("SceneFade_None", "kSceneFadeNone")
$content2 = $content2.Replace("mFrameCount", "frame_count_")
$content2 = $content2.Replace("mCowVoiceTimer", "cow_voice_timer_")
$content2 = $content2.Replace("mNextScene", "next_scene_")
$content2 = $content2.Replace("mUfoX", "ufo_x_")
$content2 = $content2.Replace("mUfoY", "ufo_y_")
$content2 = $content2.Replace("mUfoW", "ufo_w_")
$content2 = $content2.Replace("mUfoH", "ufo_h_")
$content2 = $content2.Replace("mIsAutoPatrol", "is_auto_patrol_")
$content2 = $content2.Replace("mAutoPatrolTimer", "auto_patrol_timer_")
$content2 = $content2.Replace("mbIsDraggingUfo", "is_dragging_ufo_")
$content2 = $content2.Replace("mUfoAngle", "ufo_angle_")
$content2 = $content2.Replace("mnTitleGraphHandle", "title_graph_handle_")
$content2 = $content2.Replace("mnUfoGraphHandle", "ufo_graph_handle_")
$content2 = $content2.Replace("SCENE_TITLE", "kSceneTitle")
$content2 = $content2.Replace("mbIsHoverNewGame", "is_hover_new_game_")
$content2 = $content2.Replace("mOffsetX", "offset_x_")
$content2 = $content2.Replace("mOffsetY", "offset_y_")
$content2 = $content2.Replace("mUfoVX", "ufo_vx_")
$content2 = $content2.Replace("mUfoVY", "ufo_vy_")
$content2 = $content2.Replace("rankingTitleImage", "ranking_title_image_")
$content2 = $content2.Replace("rankImage", "rank_image_")
$content2 = $content2.Replace("pointImg", "point_img_")

[System.IO.File]::WriteAllText($file2, $content2, $encUtf8)
